import type { ResumeIR } from './types.js';

function contactLine(profile: ResumeIR['profile']): string {
  const parts = [
    profile.location,
    profile.email,
    profile.github,
    profile.linkedin,
    profile.website,
  ].filter((x) => x && x.trim());
  return parts.join(' · ');
}

export function renderMarkdown(ir: ResumeIR): string {
  const { profile } = ir;
  const lines: string[] = [];

  lines.push(`# ${profile.name}`);
  if (profile.headline) lines.push(`**${profile.headline}**`);
  const contact = contactLine(profile);
  if (contact) lines.push(contact);
  lines.push('');

  if (profile.summary) {
    lines.push('## Summary');
    lines.push('');
    lines.push(profile.summary);
    lines.push('');
  }

  if (profile.specialties.length > 0) {
    lines.push('## Specialties');
    lines.push('');
    for (const s of profile.specialties) lines.push(`- ${s}`);
    lines.push('');
  }

  if (ir.experiences.length > 0) {
    lines.push('## Experience');
    lines.push('');
    for (const exp of ir.experiences) {
      const dates = exp.endDate
        ? `${exp.startDate} — ${exp.endDate}`
        : `${exp.startDate} — Present`;
      lines.push(`### ${exp.role} — ${exp.companyName}`);
      lines.push(`*${dates}*`);
      if (exp.summary) {
        lines.push('');
        lines.push(exp.summary);
      }
      if (exp.highlights.length > 0) {
        lines.push('');
        for (const h of exp.highlights) lines.push(`- ${h}`);
      }
      lines.push('');
    }
  }

  if (ir.projects.length > 0) {
    lines.push('## Projects');
    lines.push('');
    for (const project of ir.projects) {
      const meta = [project.period, project.role].filter(Boolean).join(' · ');
      lines.push(`### ${project.name}`);
      if (meta) lines.push(`*${meta}*`);
      if (project.summary) {
        lines.push('');
        lines.push(project.summary);
      }
      if (project.keyDecisions.length > 0) {
        lines.push('');
        lines.push('**Key decisions**');
        for (const d of project.keyDecisions) lines.push(`- ${d}`);
      }
      if (project.metrics.length > 0) {
        lines.push('');
        lines.push('**Metrics**');
        for (const m of project.metrics) lines.push(`- ${m}`);
      }
      if (project.technologies.length > 0) {
        lines.push('');
        lines.push(`*Stack:* ${project.technologies.join(', ')}`);
      }
      lines.push('');
    }
  }

  if (ir.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    lines.push(ir.skills.map((s) => s.name).join(', '));
    lines.push('');
  }

  if (ir.education.length > 0) {
    lines.push('## Education');
    lines.push('');
    for (const edu of ir.education) {
      lines.push(`- **${edu.name}** (${edu.type})${edu.summary ? ` — ${edu.summary}` : ''}`);
    }
    lines.push('');
  }

  if (profile.stacks.length > 0) {
    lines.push('## Technical Stacks');
    lines.push('');
    for (const s of profile.stacks) lines.push(`- ${s}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by CareerOS from the Knowledge Graph (`scope: master`).*');
  lines.push('');

  return lines.join('\n');
}
